#!/bin/bash

readonly program="$(basename "${0}")"

# Instructions
function usage {
  echo "
    Check the status code of links saved to a pinboard account.

    Bookmarks with a tag of the form 'plc-NNN' are considered OK if the status code is NNN, and not otherwise (including 200).

    Usage:
      ${program} [options]

    'token' options are compatible between pinboard-backup, pinboard-delete-unread, pinboard-link-check, pinboard-url-update, pinboard-waybackmachine

    Options:
      -r, --redirect-log      If set, links with 301 (Moved permanently) will be on their own log. Pairs well with the 'pinboard-url-update' script.
      -l, --log-dir <dir>     Directory to save logs to. Defaults to the home directory.
      -i, --include-unread    Also check unread bookmarks.
      -t, --token <token>     Your Pinboard API token.
      -a, --ask-for-token     Ask for your Pinboard API token on start.
      -s, --save-token        Save Pinboard API token to Keychain and exit. Use with '--token' or '--ask-for-token' (macOS-only).
      -h, --help              Show this message.
  " | sed -E 's/^ {4}//'
}

# Set color for verbose messages
function bad { echo "$(tput setab 1)$(tput setaf 7)${1}$(tput sgr0) ${2}" ;}
function good { echo "$(tput setab 2)$(tput setaf 7)${1}$(tput sgr0) ${2}" ;}
function warning { echo "$(tput setab 3)$(tput setaf 7)${1}$(tput sgr0) ${2}" ;}

# Options
args=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -r | --redirect-log)
      readonly redirect_log='true'
      ;;
    -l | --log-dir)
      readonly log_dir="${2}"
      shift
      ;;
    -i | --include-unread)
      readonly keep_unread='true'
      ;;
    -t | --token)
      readonly token="${2}"
      shift
      ;;
    -a | --ask-for-token)
      readonly ask_for_token='true'
      ;;
    -s | --save-token)
      readonly set_keychain_token='true'
      ;;
    --)
      shift
      args+=("${@}")
      break
      ;;
    -*)
      echo "Unrecognised option: ${1}"
      exit 1
      ;;
    *)
      args+=("${1}")
      ;;
  esac
  shift
done
set -- "${args[@]}"

# Location for log files
[[ -z "${log_dir}" ]] && readonly log_dir="${HOME}"
readonly log_file="${log_dir}/pinboardlinkcheck.log"
[[ -n "${redirect_log}" ]] && readonly redirect_log_file="${log_dir}/pinboardlinkcheck-redirects.log"

# Ask for api token, if option is set
if [[ -n "${ask_for_token}" ]]; then
  echo 'Please insert your api token (will not be echoed)'
  echo 'You can get it at https://pinboard.in/settings/password'
  read -rsp '> ' token
  echo
fi

# If no token given, look for it in the Keychain
[[ -z "${token}" ]] && readonly token="$(security find-generic-password -s 'Pinboard API Token' -w)"

# Exit if no token was set
if [[ -z "${token}" ]]; then
  echo 'Cannot continue without a Pinboard token.'
  usage
  exit 1
fi

# Check if token is correct
if ! curl --fail --silent "https://api.pinboard.in/v1/user/api_token/?auth_token=${token}" > /dev/null; then
  echo "The Pinboard API token appears to be incorrect. Alternatively, Pinboard’s servers might be down." >&2
  exit 1
fi

# Save token to Keychain
if [[ -n "${set_keychain_token}" ]]; then
  security add-generic-password -a "${token%:*}" -s 'Pinboard API Token' -w "${token}"
  exit 0
fi

# Get pinboard bookmarks
bookmarks=()

while IFS= read -r bookmark; do
  [[ "${keep_unread}" && "$(jq '.toread == "yes"')" == 'true' ]] && continue
  bookmarks+=("${bookmark}")
done < <(curl --silent "https://api.pinboard.in/v1/posts/all?auth_token=${token}&format=json" | jq --raw-output --compact-output '.[]')

readonly bookmarks

link_countdown="${#bookmarks[@]}"

# Check each link individually
for bookmark in "${bookmarks[@]}"; do
  # Output count
  echo -n "[${link_countdown}] "
  ((link_countdown--))

  # Populate tags
  tags=()

  while IFS= read -r tag; do
    tags+=("${tag}")
  done < <(jq --raw-output '.tags // "" | split(" ")[] | select(length > 0)' <<< "${bookmark}")

  # Make request to get status
  url="$(jq --raw-output '.href' <<< "${bookmark}")"
  status="$(curl --silent --write-out '%{http_code}' --output /dev/null "${url}")"

  # Some bookmarks expect a non-200 status
  ok_code='200'

  for tag in "${tags[@]}"; do
    [[ "${tag}" =~ plc-[0-9][0-9][0-9] ]] && ok_code="${tag#plc-}"
  done

  # Result
  if [[ "${status}" == "${ok_code}" ]]; then
    good "${status}" "${url}"
  elif [[ "${status:0:1}" == 3 ]]; then
    warning "${status}" "${url}"

    # Move 301 links to redirect log, if specified
    if [[ -n "${redirect_log}" ]]; then
      redirect_url="$(curl --silent --write-out '%{redirect_url}' --output /dev/null "${url}")"
      echo "${bookmark} → ${redirect_url}" >> "${redirect_log_file}"
    else
      echo "${status}" "${url}" >> "${log_file}"
    fi
  else
    bad "${status}" "${url}"
    echo "${status}" "${url}" >> "${log_file}"
  fi
done
